# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\WorkSpace\ChatRoom\Pyform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 330, 481, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.message_send = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.message_send.setGeometry(QtCore.QRect(10, 20, 461, 121))
        self.message_send.setObjectName("message_send")
        self.button_send = QtWidgets.QPushButton(self.groupBox_2)
        self.button_send.setGeometry(QtCore.QRect(200, 150, 271, 41))
        self.button_send.setObjectName("button_send")
        self.message_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.message_clear.setGeometry(QtCore.QRect(10, 150, 181, 40))
        self.message_clear.setObjectName("message_clear")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 370, 321, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.path_sendfile = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_sendfile.setGeometry(QtCore.QRect(60, 30, 251, 21))
        self.path_sendfile.setObjectName("path_sendfile")
        self.select_filepath = QtWidgets.QPushButton(self.groupBox_3)
        self.select_filepath.setGeometry(QtCore.QRect(20, 60, 81, 28))
        self.select_filepath.setObjectName("select_filepath")
        self.button_sendfile = QtWidgets.QPushButton(self.groupBox_3)
        self.button_sendfile.setGeometry(QtCore.QRect(20, 100, 291, 41))
        self.button_sendfile.setObjectName("button_sendfile")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(110, 70, 191, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 221, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_2.setObjectName("label_2")
        self.selected_user = QtWidgets.QCheckBox(self.groupBox_4)
        self.selected_user.setGeometry(QtCore.QRect(20, 80, 141, 19))
        self.selected_user.setObjectName("selected_user")
        self.username_list = QtWidgets.QComboBox(self.groupBox_4)
        self.username_list.setGeometry(QtCore.QRect(20, 50, 181, 22))
        self.username_list.setObjectName("username_list")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 20, 591, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.message_display = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.message_display.setGeometry(QtCore.QRect(20, 30, 551, 251))
        self.message_display.setObjectName("message_display")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(320, 230, 251, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("npu.png"))
        self.label_5.setObjectName("label_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 221, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.server_address = QtWidgets.QLineEdit(self.groupBox_6)
        self.server_address.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.server_address.setReadOnly(False)
        self.server_address.setObjectName("server_address")
        self.server_port = QtWidgets.QLineEdit(self.groupBox_6)
        self.server_port.setGeometry(QtCore.QRect(150, 30, 51, 21))
        self.server_port.setReadOnly(False)
        self.server_port.setObjectName("server_port")
        self.button_connect = QtWidgets.QPushButton(self.groupBox_6)
        self.button_connect.setGeometry(QtCore.QRect(10, 60, 191, 28))
        self.button_connect.setObjectName("button_connect")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 221, 101))
        self.groupBox.setObjectName("groupBox")
        self.button_login = QtWidgets.QPushButton(self.groupBox)
        self.button_login.setGeometry(QtCore.QRect(20, 50, 181, 41))
        self.button_login.setObjectName("button_login")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(80, 20, 121, 21))
        self.username.setObjectName("username")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 330, 101, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "西北工业大学自组网实验室——数据传输助手"))
        self.groupBox_2.setTitle(_translate("MainWindow", "消息发送"))
        self.button_send.setText(_translate("MainWindow", "发送"))
        self.message_clear.setText(_translate("MainWindow", "清除"))
        self.groupBox_3.setTitle(_translate("MainWindow", "文件收发"))
        self.select_filepath.setText(_translate("MainWindow", "浏览"))
        self.button_sendfile.setText(_translate("MainWindow", "发送"))
        self.label_3.setText(_translate("MainWindow", "路径"))
        self.label_6.setText(_translate("MainWindow", "请在上方指定文件发送对象"))
        self.groupBox_4.setTitle(_translate("MainWindow", "指定发送消息和文件"))
        self.label_2.setText(_translate("MainWindow", "用户列表"))
        self.selected_user.setText(_translate("MainWindow", "指定用户发送信息"))
        self.groupBox_5.setTitle(_translate("MainWindow", "消息显示"))
        self.groupBox_6.setTitle(_translate("MainWindow", "服务器IP和端口"))
        self.server_address.setText(_translate("MainWindow", "127.0.0.1"))
        self.server_port.setText(_translate("MainWindow", "12346"))
        self.button_connect.setText(_translate("MainWindow", "连接"))
        self.groupBox.setTitle(_translate("MainWindow", "用户登录"))
        self.button_login.setText(_translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_4.setText(_translate("MainWindow", "v0.11 by MYC"))
